export const REQUEST_ALL_CITIES = "REQUEST_ALL_CITIES";
export const REQUEST_ADD_CITIES = "REQUEST_ADD_CITIES";
export const CLOSE_ADD_CITY_MODAL = "CLOSE_ADD_CITY_MODAL";
export const REQUEST_DELETE_CITY = "REQUEST_DELETE_CITY";
export const CLOSE_DELETED_CITY_MODAL = "CLOSE_DELETED_CITY_MODAL";
export const REQUEST_DELETE_ALL_CITY = "REQUEST_DELETE_ALL_CITY";
export const CLOSE_DELETED_ALL_CITY_MODAL = "CLOSE_DELETED_ALL_CITY_MODAL";
export const CLOSE_EDIT_CITY_MODAL = "CLOSE_EDIT_CITY_MODAL";
export const REQUEST_EDIT_CITIES = "REQUEST_EDIT_CITIES";

export const REQUEST_ALL_SIZE = "REQUEST_ALL_SIZE";
export const REQUEST_ADD_SIZE = "REQUEST_ADD_SIZE";
export const CLOSE_ADD_SIZE_MODAL = "CLOSE_ADD_SIZE_MODAL";
export const REQUEST_DELETE_SIZE = "REQUEST_DELETE_SIZE";
export const CLOSE_DELETED_SIZE_MODAL = "CLOSE_DELETED_SIZE_MODAL";
export const REQUEST_DELETE_ALL_SIZE = "REQUEST_DELETE_ALL_SIZE";
export const CLOSE_DELETED_ALL_SIZE_MODAL = "CLOSE_DELETED_ALL_SIZE_MODAL";
export const CLOSE_EDIT_SIZE_MODAL = "CLOSE_EDIT_SIZE_MODAL";
export const REQUEST_EDIT_SIZE = "REQUEST_EDIT_SIZE";


export const REQUEST_ALL_COLOR = "REQUEST_ALL_COLOR";
export const REQUEST_ADD_COLOR = "REQUEST_ADD_COLOR";
export const CLOSE_ADD_COLOR_MODAL = "CLOSE_ADD_COLOR_MODAL";
export const REQUEST_DELETE_COLOR = "REQUEST_DELETE_COLOR";
export const CLOSE_DELETED_COLOR_MODAL = "CLOSE_DELETED_COLOR_MODAL";
export const REQUEST_DELETE_ALL_COLOR = "REQUEST_DELETE_ALL_COLOR";
export const CLOSE_DELETED_ALL_COLOR_MODAL = "CLOSE_DELETED_ALL_COLOR_MODAL";
export const CLOSE_EDIT_COLOR_MODAL = "CLOSE_EDIT_COLOR_MODAL";
export const REQUEST_EDIT_COLOR = "REQUEST_EDIT_COLOR";


export const REQUEST_ALL_TYPE = "REQUEST_ALL_TYPE";
export const REQUEST_ADD_TYPE = "REQUEST_ADD_TYPE";
export const CLOSE_ADD_TYPE_MODAL = "CLOSE_ADD_TYPE_MODAL";
export const REQUEST_DELETE_TYPE = "REQUEST_DELETE_TYPE";
export const CLOSE_DELETED_TYPE_MODAL = "CLOSE_DELETED_TYPE_MODAL";
export const REQUEST_DELETE_ALL_TYPE = "REQUEST_DELETE_ALL_TYPE";
export const CLOSE_DELETED_ALL_TYPE_MODAL = "CLOSE_DELETED_ALL_TYPE_MODAL";
export const CLOSE_EDIT_TYPE_MODAL = "CLOSE_EDIT_TYPE_MODAL";
export const REQUEST_EDIT_TYPE = "REQUEST_EDIT_TYPE";






export const REQUEST_ALL_CLIENT_ADDRESS = "REQUEST_ALL_CLIENT_ADDRESS";
export const REQUEST_DELETE_CLIENT_ADDRESS = "REQUEST_DELETE_CLIENT_ADDRESS";
export const REQUEST_EDIT_CLIENT_ADDRESS = "REQUEST_EDIT_CLIENT_ADDRESS";
export const REQUEST_ADD_CLIENT_ADDRESS = "REQUEST_ADD_CLIENT_ADDRESS";
export const REQUEST_ALL_CLIENT = "REQUEST_ALL_CLIENT";
export const REQUEST_ADD_CLIENT = "REQUEST_ADD_CLIENT";
export const CLOSE_ADD_CLIENT_MODAL = "CLOSE_ADD_CLIENT_MODAL";
export const REQUEST_DELETE_CLIENT = "REQUEST_DELETE_CLIENT";
export const CLOSE_DELETED_CLIENT_MODAL = "CLOSE_DELETED_CLIENT_MODAL";
export const REQUEST_DELETE_ALL_CLIENT = "REQUEST_DELETE_ALL_CLIENT";
export const CLOSE_DELETED_ALL_CLIENT_MODAL = "CLOSE_DELETED_ALL_CLIENT_MODAL";
export const CLOSE_EDIT_CLIENT_MODAL = "CLOSE_EDIT_CLIENT_MODAL";
export const REQUEST_EDIT_CLIENT = "REQUEST_EDIT_CLIENT";
export const SEARCH_CLIENT_BY_PHONE = "SEARCH_CLIENT_BY_PHONE";


export const REQUEST_ALL_TOWN_CITY = "REQUEST_ALL_TOWN_CITY";
export const REQUEST_ALL_TOWN = "REQUEST_ALL_TOWN";
export const REQUEST_ADD_TOWN = "REQUEST_ADD_TOWN";
export const CLOSE_ADD_TOWN_MODAL = "CLOSE_ADD_TOWN_MODAL";
export const REQUEST_DELETE_TOWN = "REQUEST_DELETE_TOWN";
export const CLOSE_DELETED_TOWN_MODAL = "CLOSE_DELETED_TOWN_MODAL";
export const REQUEST_DELETE_ALL_TOWN = "REQUEST_DELETE_ALL_TOWN";
export const CLOSE_DELETED_ALL_TOWN_MODAL = "CLOSE_DELETED_ALL_TOWN_MODAL";
export const CLOSE_EDIT_TOWN_MODAL = "CLOSE_EDIT_TOWN_MODAL";
export const REQUEST_EDIT_TOWN = "REQUEST_EDIT_TOWN";


export const REQUEST_ALL_ITEM = "REQUEST_ALL_ITEM";
export const REQUEST_ADD_ITEM = "REQUEST_ADD_ITEM";
export const CLOSE_ADD_ITEM_MODAL = "CLOSE_ADD_ITEM_MODAL";
export const REQUEST_DELETE_ITEM = "REQUEST_DELETE_ITEM";
export const CLOSE_DELETED_ITEM_MODAL = "CLOSE_DELETED_ITEM_MODAL";
export const REQUEST_DELETE_ALL_ITEM = "REQUEST_DELETE_ALL_ITEM";
export const CLOSE_DELETED_ALL_ITEM_MODAL = "CLOSE_DELETED_ALL_ITEM_MODAL";
export const CLOSE_EDIT_ITEM_MODAL = "CLOSE_EDIT_ITEM_MODAL";
export const REQUEST_EDIT_ITEM = "REQUEST_EDIT_ITEM";


export const REMOVE_ONEITEM_UPLOAD_IMG = "REMOVE_ONEITEM_UPLOAD_IMG";
export const REQUEST_ALL_ONEITEM_UPLOAD_IMG = "REQUEST_ALL_ONEITEM_UPLOAD_IMG";
export const REQUEST_ALL_ONEITEM_UPLOADS = "REQUEST_ALL_ONEITEM_UPLOADS";
export const CLOSE_ONEITEM_FILES_MODAL = "CLOSE_ONEITEM_FILES_MODAL";
export const ONEITEM_ADD_FILES = "ONEITEM_ADD_FILES";
export const ONEITEM_HAS_ERROR_MODAL = "ONE_ITEM_HAS_ERROR_MODAL";
export const ONEITEM_CLOSE_HAS_ERROR_MODAL = "ONE_ITEM_CLOSE_HAS_ERROR_MODAL";
export const REQUEST_ALL_ONEITEM = "REQUEST_ALL_ONEITEM";
export const REQUEST_ADD_ONEITEM = "REQUEST_ADD_ONEITEM";
export const CLOSE_ADD_ONEITEM_MODAL = "CLOSE_ADD_ONEITEM_MODAL";
export const REQUEST_DELETE_ONEITEM = "REQUEST_DELETE_ONEITEM";
export const CLOSE_DELETED_ONEITEM_MODAL = "CLOSE_DELETED_ONEITEM_MODAL";
export const REQUEST_DELETE_ALL_ONEITEM = "REQUEST_DELETE_ALL_ONEITEM";
export const CLOSE_DELETED_ALL_ONEITEM_MODAL = "CLOSE_DELETED_ALL_ONEITEM_MODAL";
export const CLOSE_EDIT_ONEITEM_MODAL = "CLOSE_EDIT_ONEITEM_MODAL";
export const REQUEST_EDIT_ONEITEM = "REQUEST_EDIT_ONEITEM";


export const REQUEST_ALL_ORDER_STATUS = "REQUEST_ALL_ORDER_STATUS";
export const REQUEST_ADD_ORDER_STATUS = "REQUEST_ADD_ORDER_STATUS";
export const CLOSE_ADD_ORDER_STATUS_MODAL = "CLOSE_ADD_ORDER_STATUS_MODAL";
export const REQUEST_DELETE_ORDER_STATUS = "REQUEST_DELETE_ORDER_STATUS";
export const CLOSE_DELETED_ORDER_STATUS_MODAL = "CLOSE_DELETED_ORDER_STATUS_MODAL";
export const REQUEST_DELETE_ALL_ORDER_STATUS = "REQUEST_DELETE_ALL_ORDER_STATUS";
export const CLOSE_DELETED_ALL_ORDER_STATUS_MODAL = "CLOSE_DELETED_ALL_ORDER_STATUS_MODAL";
export const CLOSE_EDIT_ORDER_STATUS_MODAL = "CLOSE_EDIT_ORDER_STATUS_MODAL";
export const REQUEST_EDIT_ORDER_STATUS = "REQUEST_EDIT_ORDER_STATUS";

export const TOGGLE_DARK = "TOGGLE_DARK";
export const TOGGLE_LANGUAGE = "TOGGLE_LANGUAGE";
